---
- hosts: opsManager
  remote_user: AZURE_SERVER_ADMIN
  tasks:
  - name: get automation apikey
    shell: mongo 127.0.0.1:27017 --quiet --eval "print(db.getSiblingDB('mmsdbconfig').config.customers.findOne().k)"
    register: opsmanager_apikey
  - debug: var=opsmanager_apikey
  - name: get automation groupid
    shell: mongo 127.0.0.1:27017 --quiet --eval "print(db.getSiblingDB('mmsdbconfig').config.customers.findOne()._id.str)" 
    register: opsmanager_groupid
  - debug: var=opsmanager_groupid
- hosts: mongoDs
  remote_user: AZURE_SERVER_ADMIN
  become: yes
  vars:
    autoagent: mongodb-mms-automation-agent-manager-latest.x86_64.rpm
  tasks:
  - name: download automation agent via http
    get_url: url="{{opsmanagerurl}}/download/agent/automation/{{autoagent}}" dest="/home/ec2-user/{{autoagent}}"
    when: ca_file.stat.exists == False
  - name: install automation agent
    yum: name=/home/AZURE_SERVER_ADMIN/{{autoagent}} state=present
  - name: update config mmsGroupId
    shell: perl -pi -e "s/mmsGroupId=/mmsGroupId={{hostvars[opsmanager]['opsmanager_groupid'].stdout_lines[0]}}/" /etc/mongodb-mms/automation-agent.config
  - name: update config mmsApiKey
    shell: perl -pi -e "s/mmsApiKey=/mmsApiKey={{hostvars[opsmanager]['opsmanager_apikey'].stdout_lines[0]}}/" /etc/mongodb-mms/automation-agent.config
  - name: update config mmsBaseUrl to http, if no ssl
    lineinfile:
      path: /etc/mongodb-mms/automation-agent.config
      regexp: '^mmsBaseUrl='
      line: 'mmsBaseUrl={{opsmanagerurl}}'
    when: ca_file.stat.exists == False
  - name: setup data directory
    file: path=/data state=directory mode=0755 owner=mongod group=mongod
  - name: start agent
    service: name=mongodb-mms-automation-agent state=started
